### PR TITLE
<CC_OS> #186 Bug Fixed

### LINKED ISSUE #186: <CC_OS> Bug found in logic of wait list asdjustment
**Describe the bug**
```c
static void __cc_sched_wait_list_adjustment(cc_sched_ctrl_t * sched_ctrl)
{
	cc_sched_tcb_t * ptr = sched_ctrl->wait_list_head;
	size_t * wait_res = ptr->wait_res.wait_on_resource;
	while(ptr != CC_OS_NULL_PTR)
	{
		ptr->wait_res.task_delay_ticks--;	/* Tick caliberations required */

		if ((wait_res != CC_OS_NULL_PTR) && (*wait_res == CC_OS_FALSE))
		{
			/* The resource is available can can go to ready state */
			ptr->wait_res.task_delay_ticks = CC_OS_FALSE;
			ptr->wait_res.wait_on_resource = CC_OS_NULL_PTR;
		}
		if(ptr->wait_res.task_delay_ticks == CC_OS_FALSE)
		{
			_cc_sched_send_to_resume(sched_ctrl, ptr);
		}
		if (ptr->wait_link.next == sched_ctrl->wait_list_head)
		{
			break;
		}
		else
		{
			ptr = ptr->wait_link.next;
		}
	}
}
```
`(*wait_res == CC_OS_FALSE)` shall be `(*wait_res != CC_OS_FALSE)`

### PR DESCRIPTION
**Pull request by pranjalchanda08**
Closes #186

### CODE REVIEW

File: src/visor/terravisor/services/kernel/cc_os_sem.c [hunk 1]
```diff
@@ -2,7 +2,7 @@
  * CYANCORE LICENSE
  * Copyrights (C) 2CC_OS_FALSE22, Cyancore Team
```
Comment (akashkollipara) [inline src/visor/terravisor/services/kernel/cc_os_sem.c:3]: 2022

File: src/visor/terravisor/services/kernel/cc_os_sched.c [hunk 2]
```diff
@@ -198,7 +198,7 @@ static void __cc_sched_wait_list_adjustment(cc_sched_ctrl_t * sched_ctrl)
 	{
 		ptr->wait_res.task_delay_ticks--;	/* Tick caliberations required */
 
-		if ((wait_res != CC_OS_NULL_PTR) && (*wait_res == CC_OS_FALSE))
+		if ((wait_res != CC_OS_NULL_PTR) && (*wait_res > CC_OS_FALSE))
```
Comment (akashkollipara) [inline src/visor/terravisor/services/kernel/cc_os_sched.c:201]: why > CC_OS_FALSE?
why not simply `&& (*wait_res)`

**Review by akashkollipara — APPROVED** [review]
